baasbox:
  ports:
  - 9000:9000/tcp
  labels:
    io.rancher.sidekicks: baasbox-data
  image: iotitude/baasbox
  volumes_from:
  - baasbox-data
baasbox-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: iotitude/baasbox-data
