This file contains the used docker composes during the Project. Some of them works and some may not work. Kaa will not work
correctly with Cassandra, not with either of these composes.

#-----------------------------------------------------------------#
# Kaa and the needed parts are here
Kaa:
  ports:
    - "22:22"
    - "8080:8080"
    - "9888:9888"
    - "9889:9889"
    - "9997:9997"
    - "9999:9999"
  #environment:
  #  BOOTSTRAP_ENABLED: 'true'
  #  CASSANDRA_HOSTS: Cassandra:9042
  #  CONTROL_ENABLED: 'true'
  #  DATABASE: cassandra
  #  JDBC_HOST: mariadb
  #  JDBC_PORT: 3306
  #  MONGODB_HOSTS: mongodbhost:27017
  #  OPERATIONS_ENABLED: 'true'
  #  ZK_HOSTS: zookeeper:2181
  labels:
    io.rancher.container.pull_image: always
    io.rancher.sidekicks: cassandra
  command: bash -c "/usr/bin/kaa-node start && while true; do sleep 1; done"
  tty: true
  image: supermies/kaa
  links:
  - mariadb
  - cassandra:cassandra
  - zookeeper
  stdin_open: true
cassandra:
  ports:
  - "9042:9042"
  - "9160:9160"
  environment:
    RANCHER_ENABLE: 'true'
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: pboos/rancher-cassandra:3.1
  volumes:
  - /var/lib/cassandra
  stdin_open: true
zookeeper:
  ports:
  - 2181:2181/tcp
  tty: true
  hostname: zookeeper
  image: supermies/zookeeper
  links:
  - cassandra:cassandra
  - mariadb
  volumes:
  - /opt/zk/data
mariadb:
  image: mariadb:5.5
  environment:
    MYSQL_ROOT_PASSWORD: maria
    MYSQL_DATABASE: kaa
    MYSQL_USER: sqladmin
    MYSQL_PASSWORD: adminkadmin
  expose:
  - "3306"
#-----------------------------------------------------------------#
  
# One container Kaa is found below:
#-----------------------------------------------------------------#
kaa:
  ports:
  - 22:22/tcp
  - 8080:8080/tcp
  - 9888:9888/tcp
  - 9889:9889/tcp
  - 9997:9997/tcp
  - 9999:9999/tcp
  image: iotitude/kaa_single_container
#-----------------------------------------------------------------#
  
#-----------------------------------------------------------------#
  # Baasbox stuff is over here
baasbox:
  ports:
  - 9000:9000/tcp
  labels:
    io.rancher.sidekicks: baasbox-data
  image: iotitude/baasbox
  volumes_from:
  - baasbox-data
baasbox-data:
  labels:
    io.rancher.container.start_once: 'true'
  image: iotitude/baasbox-data
#-----------------------------------------------------------------#

#-----------------------------------------------------------------#
# Jenkins compose
jenkinsmaster:
  ports:
  - 40000:40000/tcp
  - 49001:8080/tcp
  labels:
    io.rancher.sidekicks: jenkinsdata,jenkinsslave
  image: iotitude/jenkins-master
  volumes_from:
  - jenkinsdata
jenkinsdata:
  labels:
    io.rancher.container.start_once: 'true'
  image: iotitude/jenkins-data
jenkinsslave:
  image: iotitude/jenkins-slave
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  volumes_from:
  - jenkinsdata
jenkinsnginx:
  ports:
  - 8088:8088/tcp
  image: iotitude/jenkins-nginx
  links:
  - jenkinsmaster:jenkins-master
#-----------------------------------------------------------------#

#-----------------------------------------------------------------#
# This is the compose for Cassandra that was used for data generation
Cassandra:
  ports:
  - 9042:9042/tcp
  - 9160:9160/tcp
  environment:
    RANCHER_ENABLE: 'true'
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: pboos/rancher-cassandra
  volumes:
  - /var/lib/cassandra
  stdin_open: true
#-----------------------------------------------------------------#

#-----------------------------------------------------------------#
# Compose for Portal service:
portal:
  ports:
  - 3000:3000/tcp
  - 3001:3001/tcp
  labels:
    io.rancher.scheduler.affinity:host_label: portal=1
  image: iotitude/portal
#-----------------------------------------------------------------#

#-----------------------------------------------------------------#
# Zeppelin compose used in the Project. This one needs one more .jar file to work, which it does not have.
# Possible file needed is 'guava-16.0.1.jar'.
zeppelin:
  ports:
  - 8080:8080/tcp
  image: dylanmei/zeppelin:0.6.0-stable
#-----------------------------------------------------------------#
